image: ubuntu:24.04

build-docs:
  script:
    - apt-get update && apt-get install -y build-essential make curl wget git libfftw3-dev pandoc
                                           #ffmpeg texlive-full
    # - EXTRAS=doc make tools
    - bash <(curl -L https://pixi.sh/install.sh)
    - export PATH=/root/.pixi/bin/:${PATH}
    #- bash <(curl -L micro.mamba.pm/install.sh)
    # - source ~/.bashrc  # This does not work in CI for some reason.  Not a login shell?
    #- export PATH=/root/.local/bin/:${PATH}
    - EXTRAS=doc make html
    - mv Docs/build/html public
  pages: true  # specifies that this is a Pages job
  artifacts:
    paths:
      - public
  rules:
    # Only run the CI if the commit message has "DOC" in it.
    - if: $CI_COMMIT_MESSAGE =~ "/DOC/"
