name: _mmfutils
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.6,<3.9

  # Better to install these from conda for performance.
  - numpy >=1.15.4
  - numba
  - pyfftw
  - cython
  
  - pip
  - pip:
    - .[test,doc]
