name: _mmfutils
channels:
  - defaults
dependencies:
  - python~=3.9
  - ipykernel

  # Better to install these from conda for performance.
  - numpy >=1.15.4
  - numba
  - cython
  - conda-forge::pyfftw
  
  - pip
  - pip:
    - .[test,doc]
