# Some parts of this Makefile serve as a conversion from micromamba to pixi.
# Targets with a trailing underscore represent the micromamba version.

SHELL = /bin/bash
_SHELL = $(notdir $(SHELL))

PY ?= 3.14
DEV_PY_VER ?= $(PY)
PY_VERS ?= 3.9 3.10 3.11 3.12 3.13 3.14
PANDOC_FLAGS ?= --toc --standalone

USE_MICROMAMBA ?= true
USE_ROSETTA ?= false

CHANNEL ?= conda-forge

ENVS_ ?= envs
BIN ?= build/bin
PDM ?= pdm
PIXI ?= pixi
ENV ?= $(subst .,,py$(DEV_PY_VER))
ENV_TEST ?= $(subst .,,test$(DEV_PY_VER))

# Generate github workflows.  Although nox will run all the tests for us, we make
# separate workflows for github so that we can have indepdent badges for each
# set of tests.
GITHUB_CI_DIR ?= .github/workflows
GITHUB_CI_FILES ?= $(patsubst %,$(GITHUB_CI_DIR)/python_%.yaml,$(PY_VERS))

# If defined, then assume we are running on a CI. For example, don't run tests in parallel
# threads.
CI ?= 

# Customize extras here pip install .[$(EXTRAS)]
EXTRAS ?= test,doc,notebook

# Set if you want editable installs for developing
EDITABLE ?= true

# ------- Computed variables ------
ifeq ($(USE_MICROMAMBA), true)
  CONDA ?= $(CONDA_PRE) micromamba
	CONDA_ENV = $(CONDA)
  _MICROMAMBA = eval "$$(micromamba shell hook --shell=bash 2> /dev/null)" && micromamba
else
  CONDA ?= $(CONDA_PRE) conda
	CONDA_ENV = $(CONDA) env
  _MICROMAMBA = source $$($(CONDA) info --base)/etc/profile.d/conda.sh && $(CONDA)
endif

CONDA_ACTIVATE ?= $(_MICROMAMBA) activate

# We need special effects for 
ifeq ($(USE_ROSETTA), true)
  ifeq ($(shell uname -p),arm)
    PLATFORM = arm64
    CONDA_PRE += CONDA_SUBDIR=osx-64
  endif
endif

DEV_ENV_ ?= $(ENVS_)/py$(DEV_PY_VER)
CONDA_ACTIVATE_DEV = $(CONDA_ACTIVATE) $(DEV_ENV_)
RUN_ = $(_MICROMAMBA) run -p $(DEV_ENV_)
RUN = $(PIXI) run -e $(ENV)
ALL_ENVS_ = $(foreach py,$(PY_VERS),$(ENVS_)/py$(py))
ALL_PIXI_ENVS ?= $(foreach py,$(PY_VERS),$(subst .,,py$(py) test$(py)))

# ------- Top-level targets  -------
# Default prints a help message
.PHONY: help usage shell_ shell
help:
	@make usage

usage:
	@echo "$$HELP_MESSAGE"

shell_: dev_
	#$(CONDA_ACTIVATE_DEV) && $(PDM) install $(PDM_EXTRAS)
	$(RUN_) bash --init-file .init-file.micromamba.bash

shell:
	$(RUN) bash --init-file .init-file.pixi.bash

qshell: dev_
	$(RUN_) bash --init-file .init-file.bash

######################################################################
# Tests
.PHONY: test

ifndef CI
PYTESTARGS ?= -n 10
endif

test:
	#$(CONDA_ACTIVATE_DEV) && pytest $(PYTESTARGS)
	$(PIXI) run -e $(ENV_TEST) pytest $(PYTESTARGS)


######################################################################
# Documentation
.PHONY: html

DOC_REQUIREMENTS =

html:
	$(RUN) make -C Docs/ html

html_: dev_
	$(RUN_) make -C Docs/ html

README.rst: Docs/README.ipynb
	# Not sure why we need the ../ for --output=
	jupyter nbconvert --to=rst --output=../README.rst Docs/README.ipynb

%.html: %.rst
	rst2html5.py $< > $@

# Running make <name>.html will use fswatch to look for modifications in the corresponding
# <name>.md file and will use pandoc to generate the html file, then calling $(OPEN_BROWSER)
# to show this. We then run fswatch to look over this looking for changes.  Once the user
# exits with a keyboard interrupt, the intermediate html file is removed.  We use Safari
# as the default browser on Mac OS X because Chrome-based browsers steal focus.
BROWSER ?= "Brave Browser"
BROWSER ?= "Safari"
OPEN_BROWSER ?= open -g -a $(BROWSER) $@
REFRESH_BROWSER ?= osascript -e 'tell application $(BROWSER) to tell the active tab of its first window to reload'
REFRESH_BROWSER ?= $(OPEN_BROWSER)
PANDOC_FLAGS ?= -s
PANDOC ?= pandoc $(PANDOC_FLAGS) --metadata title=\"$*\" $< -o $@
FSWATCH ?= fswatch -e ".*" -i "$<" -o . 
%.html: %.md
	$(PANDOC) && $(OPEN_BROWSER)
	$(FSWATCH) | while read num; do $(PANDOC) && $(REFRESH_BROWSER); done

######################################################################
# GitHub Workflows
.PHONY: workflows

define _workflow_test_file
# DO NOT EDIT!
# This file is generated by running make workflows.  
name: python-V.XX
on: push
jobs:
  pyV-XX:
    uses: ./.github/workflows/tests.yaml
    with:
      python_version: 'V.XX'
endef

export _workflow_test_file

$(GITHUB_CI_DIR)/python_%.yaml: Makefile
	echo "$$_workflow_test_file" | sed "s/V\.XX/$*/g" | sed "s/V-XX/$(subst .,-,$*)/g" > $@

workflows: $(GITHUB_CI_FILES)

######################################################################
# Development Environments etc.
.PHONY: dev_ dev

ifeq ($(EDITABLE), true)
  PIP_INSTALL_ARGS += -e
endif

dev_: $(DEV_ENV_)
	$(CONDA_ACTIVATE_DEV) && python3 -m pip install $(PIP_INSTALL_ARGS) .[$(strip  $(EXTRAS))]

dev:
	pixi install

$(ENVS_): $(ALL_ENVS_)

$(ENVS_)/py3.11: environment.yaml pyproject.toml
	$(CONDA_ENV) create -y -c $(CHANNEL) -p $@ -f $< $(GPU_PACKAGES) "conda-forge::python=3.11"
ifneq ($(USE_MICROMAMBA), true)
  ifeq ($(shell uname -p),arm)
	  $(CONDA_ACTIVATE) $@ && $(CONDA) config --env --set subdir osx-64
  endif
endif
	mkdir -p $(BIN)
	ln -fs $(abspath $@/bin/python$*) $(BIN)/
	@# Upgrade pip: https://github.com/conda/conda/issues/11931
	@# Install pdm: https://github.com/pdm-project/pdm/discussions/1758#discussioncomment-5333094
	$(CONDA_ACTIVATE_DEV) && pip install --upgrade pip pdm setuptools
	$(CONDA_ACTIVATE_DEV) && $(PDM) install $(PDM_EXTRAS)

$(ENVS_)/py%: environment.yaml pyproject.toml
	$(CONDA_ENV) create -y -c $(CHANNEL) -p $@ -f $< $(GPU_PACKAGES) "python=$*"
ifneq ($(USE_MICROMAMBA), true)
  ifeq ($(shell uname -p),arm)
	  $(CONDA_ACTIVATE) $@ && $(CONDA) config --env --set subdir osx-64
  endif
endif
	mkdir -p $(BIN)
	ln -fs $(abspath $</bin/python$*) $@

pdm.lock: environment.yaml pyproject.toml
	$(CONDA_ACTIVATE_DEV) && for py in $(PY_VERS); do $(PDM) lock --python="$${py}.*" --append; done

####################
# Pixi versions

.PHONE: all_pixi_envs
all_pixi_envs:
	$(PIXI) install $(foreach env,$(ALL_PIXI_ENVS),-e $(env))

######################################################################
# Documentation
.PHONY: doc-server

doc-server:
	$(RUN) myst start #--execute

######################################################################
# Cleaning
.PHONY: clean realclean

clean:
	-coverage erase
	$(RM) -r fil-result
	find . -type d -name "htmlcov"  -exec $(RM) -r {} +
	find . -type d -name "__pycache__" -exec $(RM) -r {} +
	find . -type f -name "*.pyc" -delete
	find . -type f -name "*.pyo" -delete
	$(RM) -r src/mmfutils.egg-info
	$(RM) -r Docs/README_files/
	$(RM) *.html

realclean: clean
	$(PIXI) clean
	$(RM) -r .nox .conda $(ENVS) $(BIN)
	$(RM) -r build


######################################################################
# Usage

define HELP_MESSAGE

This Makefile provides several tools for creating a development environment for testing, etc.
The main objective is to provide support for different architectures, specifically
on platforms like Mac OS X with an ARM processor.  At the time of writing, the tests fail
because pyFFTW does not build (see https://github.com/pyFFTW/pyFFTW/issues/144).  To get
arround this, we use various stratgies for installing python appropriately using Rosetta
for example.

Variables:
   DEV_PY_VER: (= "$(DEV_PY_VER)")
                     Version of python for development.  For convenience one can use `PY`, e.g.
                     `PY=3.9 make test`
   PY_VERS: (= "$(PY_VERS)")
                     Versions of python to use for testing, and to completely install
                     environments for.
   ENV: (= "$(ENV)")
                     Pixi environment to use for running commands.  This allows you to
                     specify specific interpreters.  Options included
                     `default`, `py39`, ..., `py314`, `test39`, ..., `test214` etc.
                     Run `pixi info` for details.  By default this is set from `DEV_PY_VER`.
   ENV_TEST: (= "$(ENV_TEST)")
                     Pixi environment to use for running tests. Default set from `DEV_PY_VER`.
   ENVS_: (= "$(ENVS_)")
                     Location ofenvironments created by `micromamba`.  Pixi environments
                     are stored in `.pixi/envs` or the location specified by the
                     `detached-environments` configuration.  I do not see a way to
                     customize this locally. See
       https://pixi.prefix.dev/latest/reference/pixi_configuration/#detached-environments
   DEV_ENV_: (= "$(DEV_ENV_)")
                     Python development environment for micromamba.
   PANDOC_FLAGS: (= "$(PANDOC_FLAGS)")
                     Flags to pass to pandoc for generating HTML files from markdown files.
   CONDA_PRE: (= "$(CONDA_PRE)")
                     Comes before the conda command.  Use for CONDA_SUB= for example.
   CONDA: (= "$(CONDA)")
                     Command to run conda (includes/overrrides CONDA_PRE).
   CONDA_ACTIVATE: (= "$(CONDA_ACTIVATE)")
                     Command to run conda activate.  This can be tricky in a Makefile, so
                     we allow this to be customized.  See:
                     https://stackoverflow.com/questions/53382383
	                   https://stackoverflow.com/questions/60115420
   BIN: (= "$(BIN)")
                     Binary directory to symlink locally install versions of python.
                     Add this to the path so that nox will find them.

   EXTRAS: (= "$(EXTRAS)")
                     Extras to install with the project.  The defalt is `all`, which
                     includes everything needed to make the documentation, testing,
                     for running notebooks, etc.  If you just need to run the package,
                     Then you might like to make this `full` or `full,tests` to simplify.
   PDM_EXTRAS: (= "$(PDM_EXTRAS)")
                     Extras (groups) for PDM to install in the DEV_ENV.  Typically this
                     is `-d -G :all` for everything, but on some platforms or with
                     advanced versions of `PY_VER` you may to restrict this.  If you do
                     need to restruct this, I recommend adding some conditional code here
                     for future records.  If you change this, don't forget to include the
                     dev dependencies (`-d`) unless they are also problematic.

Computed variables (cannot be overwritten on command line)
	 CONDA_ACTIVATE_DEV:(= "$(CONDA_ACTIVATE_DEV)")
                     Command to activate the development environment.
	 ALL_ENVS_: (= "$(ALL_ENVS_)")
                     All environments that will be made for micromamba.
	 ALL_PIXI_ENVS: (= "$(ALL_PIXI_ENVS)")
                     All environments that will be made for pixi.

Initialization:
   make shell        Spawn a shell after building and checking the dev environment.
   make qshell       Quickly spawn a shell.  Environment not checked (created if needed).
   make dev          Initialize the development environment and setup poetry.
   make $(ENVS_)
                     Initialize all environments (micromamba).
   make all_pixi_envs
                     Initialize all environments in `ALL_PIXI_ENVS` (pixi).
   
Testing:
   make test         Runs the general tests in the dev environment.

Maintenance:
   make clean        Clean repo.
   make realclean    Remove all envs, etc.

Documentation:
   make html         Build the Sphinx documentation.
   make README.rst   Generate the README.rst file from doc/README.ipynb
   make Notes.html   Build and serve Notes.md

endef
export HELP_MESSAGE
