# .github/workflows/tests.yaml
# Based on
# https://github.com/orgs/community/discussions/52616
# https://docs.github.com/en/actions/use-cases-and-examples/building-and-testing/building-and-testing-python#using-multiple-python-versions

name: Run Tests

on:
  # workflow_call is a required field of the "on" property,
  # when intending to use the workflow as a reusable workflow
  workflow_call:
    inputs:
      python_version:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      # Store your packages in .github/apt-packages.txt
      - name: Load package list
        id: package_list
        run: echo "PACKAGES=$(tr '\n' ' ' < .github/apt-packages.txt)" >> $GITHUB_ENV

      - name: Prepare APT cache dir and symlink
        run: |
          mkdir -p .apt-cache/archives/partial
          sudo rm -rf /var/cache/apt/archives
          sudo ln -s "$PWD/.apt-cache/archives" /var/cache/apt/archives
          
      - name: Cache APT archive
        id: cache-apt-archive
        uses: actions/cache@v5
        with:
          path: .apt-cache/archives
          key: |
            ${{ runner.os }}-apt-cache-${{ hashFiles('.github/apt-packages.txt') }}
          restore-keys: |
            ${{ runner.os }}-apt-cache-
            
      - name: Download APT files
        if: steps.cache-apt-archive.outputs.cache-hit != 'true'
        run: |        
          # https://github.com/actions/runner-images/issues/6894#issuecomment-1378055030
          sudo apt-get --option="APT::Acquire::Retries=3" update
          sudo apt-get --option="APT::Acquire::Retries=3" install -y -d $PACKAGES

      - name: Install from APT Cache
        run: sudo apt-get install -y $PACKAGES

      - name: Clean APT Cache locks & fix permissions
        if: always()
        run: |
          sudo rm -f /var/cache/apt/archives/lock
          #sudo rm -f /var/lib/dpkg/lock-frontend || true
          #sudo rm -f /var/lib/apt/lists/lock || true
          sudo chown -R $USER:$USER .apt-cache/archives
        
      #- name: Install TeXLive
      #  run: |        
      #    # https://gist.github.com/wkrea/b91e3d14f35d741cf6b05e57dfad8faf
      #    sudo apt-get --option="APT::Acquire::Retries=3" install texlive-full
      #    # sudo apt-get --option="APT::Acquire::Retries=3" install `sudo apt --assume-no install texlive-full | \
      #    #  awk '/The following additional packages will be installed/{f=1;next} /Suggested packages/{f=0} f' | \
      #    #  tr ' ' '\n' | grep -vP 'doc$' | grep -vP 'texlive-lang' | grep -vP 'latex-cjk' | tr '\n' ' '`
      - name: Install Pixi
        run: |
          curl -fsSL https://pixi.sh/install.sh | sh
          echo "/home/runner/.pixi/bin" >> $GITHUB_PATH
      - name: Run Tests
        run: PY=${{ inputs.python_version }} make test
      #- name: Upload coverage data
      #  uses: actions/upload-artifact@v4
      #  with:
      #    name: coverage-data-${{ inputs.python_version }}
      #    path: .coverage.*
      #    include-hidden-files: true
      #    if-no-files-found: ignore
